# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class UI_Index(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(815, 614)
        MainWindow.setMinimumSize(QtCore.QSize(815, 614))
        MainWindow.setMaximumSize(QtCore.QSize(815, 614))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 815, 614))
        self.tabWidget.setMinimumSize(QtCore.QSize(815, 614))
        self.tabWidget.setMaximumSize(QtCore.QSize(815, 614))
        self.tabWidget.setObjectName("tabWidget")
        self.widget = QtWidgets.QWidget()
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(230, 10, 48, 23))
        self.label.setStyleSheet("font: 14pt \"楷体\";")
        self.label.setObjectName("label")
        self.webUrl = QtWidgets.QLineEdit(self.widget)
        self.webUrl.setGeometry(QtCore.QRect(290, 10, 171, 21))
        self.webUrl.setMaximumSize(QtCore.QSize(16777215, 45))
        self.webUrl.setObjectName("webUrl")
        self.submit = QtWidgets.QPushButton(self.widget)
        self.submit.setGeometry(QtCore.QRect(480, 10, 93, 32))
        self.submit.setStyleSheet("font: 14pt \"楷体\";")
        self.submit.setObjectName("submit")
        self.webView = QtWebEngineWidgets.QWebEngineView(self.widget)
        self.webView.setGeometry(QtCore.QRect(280, 60, 511, 501))
        self.webView.setUrl(QtCore.QUrl("https://www.baidu.com/"))
        self.webView.setZoomFactor(0.6)
        self.webView.setObjectName("webView")
        self.tableView = QtWidgets.QTableView(self.widget)
        self.tableView.setGeometry(QtCore.QRect(10, 60, 251, 481))
        self.tableView.setObjectName("tableView")
        self.tabWidget.addTab(self.widget, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.label_3 = QtWidgets.QLabel(self.tab_2)
        self.label_3.setGeometry(QtCore.QRect(80, 20, 48, 23))
        self.label_3.setStyleSheet("font: 14pt \"楷体\";")
        self.label_3.setObjectName("label_3")
        self.webUrlAttack = QtWidgets.QLineEdit(self.tab_2)
        self.webUrlAttack.setGeometry(QtCore.QRect(150, 20, 171, 21))
        self.webUrlAttack.setMaximumSize(QtCore.QSize(16777215, 45))
        self.webUrlAttack.setObjectName("webUrlAttack")
        self.submitAttack = QtWidgets.QPushButton(self.tab_2)
        self.submitAttack.setGeometry(QtCore.QRect(590, 20, 93, 32))
        self.submitAttack.setStyleSheet("font: 14pt \"楷体\";")
        self.submitAttack.setObjectName("submitAttack")
        self.webUrlAttackThreadNum = QtWidgets.QLineEdit(self.tab_2)
        self.webUrlAttackThreadNum.setGeometry(QtCore.QRect(450, 20, 101, 21))
        self.webUrlAttackThreadNum.setMaximumSize(QtCore.QSize(16777215, 45))
        self.webUrlAttackThreadNum.setObjectName("webUrlAttackThreadNum")
        self.label_4 = QtWidgets.QLabel(self.tab_2)
        self.label_4.setGeometry(QtCore.QRect(360, 20, 71, 23))
        self.label_4.setStyleSheet("font: 14pt \"楷体\";")
        self.label_4.setObjectName("label_4")
        self.textEdit = QtWidgets.QTextEdit(self.tab_2)
        self.textEdit.setGeometry(QtCore.QRect(10, 70, 791, 461))
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.symCombBox = QtWidgets.QComboBox(self.tab)
        self.symCombBox.setGeometry(QtCore.QRect(300, 20, 111, 31))
        self.symCombBox.setObjectName("symCombBox")
        self.symCombBox.addItem("")
        self.symCombBox.addItem("")
        self.symCombBox.addItem("")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(190, 20, 101, 31))
        self.label_2.setStyleSheet("font: 14pt \"楷体\";")
        self.label_2.setObjectName("label_2")
        self.symKey = QtWidgets.QTextEdit(self.tab)
        self.symKey.setGeometry(QtCore.QRect(410, 110, 371, 91))
        self.symKey.setObjectName("symKey")
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setGeometry(QtCore.QRect(410, 70, 101, 31))
        self.label_6.setStyleSheet("font: 14pt \"楷体\";")
        self.label_6.setObjectName("label_6")
        self.symResult = QtWidgets.QTextEdit(self.tab)
        self.symResult.setGeometry(QtCore.QRect(410, 260, 371, 271))
        self.symResult.setObjectName("symResult")
        self.label_7 = QtWidgets.QLabel(self.tab)
        self.label_7.setGeometry(QtCore.QRect(410, 220, 101, 31))
        self.label_7.setStyleSheet("font: 14pt \"楷体\";")
        self.label_7.setObjectName("label_7")
        self.symContent = QtWidgets.QTextEdit(self.tab)
        self.symContent.setGeometry(QtCore.QRect(20, 110, 341, 421))
        self.symContent.setObjectName("symContent")
        self.label_8 = QtWidgets.QLabel(self.tab)
        self.label_8.setGeometry(QtCore.QRect(20, 70, 101, 31))
        self.label_8.setStyleSheet("font: 14pt \"楷体\";")
        self.label_8.setObjectName("label_8")
        self.symEncryptionBtn = QtWidgets.QPushButton(self.tab)
        self.symEncryptionBtn.setGeometry(QtCore.QRect(450, 20, 71, 41))
        self.symEncryptionBtn.setStyleSheet("font: 14pt \"楷体\";")
        self.symEncryptionBtn.setObjectName("symEncryptionBtn")
        self.symDecipherBtn = QtWidgets.QPushButton(self.tab)
        self.symDecipherBtn.setGeometry(QtCore.QRect(540, 20, 71, 41))
        self.symDecipherBtn.setStyleSheet("font: 14pt \"楷体\";")
        self.symDecipherBtn.setObjectName("symDecipherBtn")
        self.tabWidget.addTab(self.tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.label_9 = QtWidgets.QLabel(self.tab_3)
        self.label_9.setGeometry(QtCore.QRect(20, 220, 101, 31))
        self.label_9.setStyleSheet("font: 14pt \"楷体\";")
        self.label_9.setObjectName("label_9")
        self.asymResult = QtWidgets.QTextEdit(self.tab_3)
        self.asymResult.setGeometry(QtCore.QRect(410, 260, 371, 271))
        self.asymResult.setObjectName("asymResult")
        self.asymPrivateKey = QtWidgets.QTextEdit(self.tab_3)
        self.asymPrivateKey.setGeometry(QtCore.QRect(410, 110, 371, 91))
        self.asymPrivateKey.setObjectName("asymPrivateKey")
        self.label_10 = QtWidgets.QLabel(self.tab_3)
        self.label_10.setGeometry(QtCore.QRect(410, 70, 101, 31))
        self.label_10.setStyleSheet("font: 14pt \"楷体\";")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.tab_3)
        self.label_11.setGeometry(QtCore.QRect(410, 220, 101, 31))
        self.label_11.setStyleSheet("font: 14pt \"楷体\";")
        self.label_11.setObjectName("label_11")
        self.asymCombBox = QtWidgets.QComboBox(self.tab_3)
        self.asymCombBox.setGeometry(QtCore.QRect(310, 20, 111, 31))
        self.asymCombBox.setObjectName("asymCombBox")
        self.asymCombBox.addItem("")
        self.asymCombBox.addItem("")
        self.asymCombBox.addItem("")
        self.asymContent = QtWidgets.QTextEdit(self.tab_3)
        self.asymContent.setGeometry(QtCore.QRect(20, 260, 371, 271))
        self.asymContent.setObjectName("asymContent")
        self.label_5 = QtWidgets.QLabel(self.tab_3)
        self.label_5.setGeometry(QtCore.QRect(200, 20, 101, 31))
        self.label_5.setStyleSheet("font: 14pt \"楷体\";")
        self.label_5.setObjectName("label_5")
        self.asymPublicKey = QtWidgets.QTextEdit(self.tab_3)
        self.asymPublicKey.setGeometry(QtCore.QRect(20, 110, 371, 91))
        self.asymPublicKey.setObjectName("asymPublicKey")
        self.label_12 = QtWidgets.QLabel(self.tab_3)
        self.label_12.setGeometry(QtCore.QRect(20, 70, 101, 31))
        self.label_12.setStyleSheet("font: 14pt \"楷体\";")
        self.label_12.setObjectName("label_12")
        self.asymDecipherBtn = QtWidgets.QPushButton(self.tab_3)
        self.asymDecipherBtn.setGeometry(QtCore.QRect(540, 20, 71, 41))
        self.asymDecipherBtn.setStyleSheet("font: 14pt \"楷体\";")
        self.asymDecipherBtn.setObjectName("asymDecipherBtn")
        self.asymEncryptionBtn = QtWidgets.QPushButton(self.tab_3)
        self.asymEncryptionBtn.setGeometry(QtCore.QRect(450, 20, 71, 41))
        self.asymEncryptionBtn.setStyleSheet("font: 14pt \"楷体\";")
        self.asymEncryptionBtn.setObjectName("asymEncryptionBtn")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.label_13 = QtWidgets.QLabel(self.tab_4)
        self.label_13.setGeometry(QtCore.QRect(230, 20, 101, 31))
        self.label_13.setStyleSheet("font: 14pt \"楷体\";")
        self.label_13.setObjectName("label_13")
        self.otherEncryptionBtn = QtWidgets.QPushButton(self.tab_4)
        self.otherEncryptionBtn.setGeometry(QtCore.QRect(480, 20, 71, 41))
        self.otherEncryptionBtn.setStyleSheet("font: 14pt \"楷体\";")
        self.otherEncryptionBtn.setObjectName("otherEncryptionBtn")
        self.otherCombBox = QtWidgets.QComboBox(self.tab_4)
        self.otherCombBox.setGeometry(QtCore.QRect(340, 20, 111, 31))
        self.otherCombBox.setObjectName("otherCombBox")
        self.otherCombBox.addItem("")
        self.otherCombBox.addItem("")
        self.otherCombBox.addItem("")
        self.label_14 = QtWidgets.QLabel(self.tab_4)
        self.label_14.setGeometry(QtCore.QRect(30, 70, 101, 31))
        self.label_14.setStyleSheet("font: 14pt \"楷体\";")
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.tab_4)
        self.label_15.setGeometry(QtCore.QRect(420, 70, 101, 31))
        self.label_15.setStyleSheet("font: 14pt \"楷体\";")
        self.label_15.setObjectName("label_15")
        self.otherContent = QtWidgets.QTextEdit(self.tab_4)
        self.otherContent.setGeometry(QtCore.QRect(30, 110, 371, 421))
        self.otherContent.setObjectName("otherContent")
        self.otherResult = QtWidgets.QTextEdit(self.tab_4)
        self.otherResult.setGeometry(QtCore.QRect(420, 110, 371, 421))
        self.otherResult.setObjectName("otherResult")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.apiTable = QtWidgets.QTableView(self.tab_5)
        self.apiTable.setGeometry(QtCore.QRect(10, 110, 221, 420))
        self.apiTable.setObjectName("apiTable")
        # self.apiTable.setColumnCount(0)
        # self.apiTable.setRowCount(0)
        self.injectEdit = QtWidgets.QTextEdit(self.tab_5)
        self.injectEdit.setGeometry(QtCore.QRect(240, 10, 241, 80))
        self.injectEdit.setObjectName("injectEdit")
        self.injectConsole = QtWidgets.QTextEdit(self.tab_5)
        self.injectConsole.setGeometry(QtCore.QRect(240, 110, 561, 420))
        self.injectConsole.setObjectName("injectConsole")
        self.injectBtn = QtWidgets.QPushButton(self.tab_5)
        self.injectBtn.setGeometry(QtCore.QRect(500, 10, 93, 32))
        self.injectBtn.setStyleSheet("font: 14pt \"楷体\";")
        self.injectBtn.setObjectName("injectBtn")
        self.injectApi = QtWidgets.QLabel(self.tab_5)
        self.injectApi.setGeometry(QtCore.QRect(80, 20, 141, 31))
        self.injectApi.setStyleSheet("font: 14pt \"楷体\";")
        self.injectApi.setText("")
        self.injectApi.setObjectName("injectApi")
        self.label_16 = QtWidgets.QLabel(self.tab_5)
        self.label_16.setGeometry(QtCore.QRect(10, 30, 72, 15))
        self.label_16.setObjectName("label_16")
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.leakScanUrl = QtWidgets.QLineEdit(self.tab_6)
        self.leakScanUrl.setGeometry(QtCore.QRect(240, 30, 200, 25))
        self.leakScanUrl.setObjectName("leakScanUrl")
        self.label_17 = QtWidgets.QLabel(self.tab_6)
        self.label_17.setGeometry(QtCore.QRect(180, 30, 61, 31))
        self.label_17.setStyleSheet("font: 14pt \"楷体\";")
        self.label_17.setObjectName("label_17")
        self.leakScanBtn = QtWidgets.QPushButton(self.tab_6)
        self.leakScanBtn.setGeometry(QtCore.QRect(460, 30, 93, 32))
        self.leakScanBtn.setStyleSheet("font: 14pt \"楷体\";")
        self.leakScanBtn.setObjectName("leakScanBtn")
        self.leakScanConsole = QtWidgets.QTextEdit(self.tab_6)
        self.leakScanConsole.setGeometry(QtCore.QRect(13, 76, 791, 461))
        self.leakScanConsole.setObjectName("leakScanConsole")
        self.leakScanStopBtn = QtWidgets.QPushButton(self.tab_6)
        self.leakScanStopBtn.setGeometry(QtCore.QRect(570, 30, 93, 32))
        self.leakScanStopBtn.setStyleSheet("font: 14pt \"楷体\";")
        self.leakScanStopBtn.setObjectName("leakScanStopBtn")
        self.tabWidget.addTab(self.tab_6, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 815, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(6)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "信息安全检测平台"))
        # self.tabWidget.setToolTip(_translate("MainWindow", "<html><head/><body><p>注入测试</p></body></html>"))
        # self.tabWidget.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>注入测试</p></body></html>"))
        self.label.setText(_translate("MainWindow", "网址"))
        self.submit.setText(_translate("MainWindow", "分析"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.widget), _translate("MainWindow", "网址分析"))
        self.label_3.setText(_translate("MainWindow", "网址"))
        self.submitAttack.setText(_translate("MainWindow", "开始"))
        self.label_4.setText(_translate("MainWindow", "线程数"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "网站攻击"))
        self.symCombBox.setItemText(0, _translate("MainWindow", "DES"))
        self.symCombBox.setItemText(1, _translate("MainWindow", "AES"))
        self.symCombBox.setItemText(2, _translate("MainWindow", "3DES"))
        self.label_2.setText(_translate("MainWindow", "加密算法"))
        self.label_6.setText(_translate("MainWindow", "密钥"))
        self.label_7.setText(_translate("MainWindow", "加密结果"))
        self.label_8.setText(_translate("MainWindow", "加密内容"))
        self.symEncryptionBtn.setText(_translate("MainWindow", "加密"))
        self.symDecipherBtn.setText(_translate("MainWindow", "解密"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "对称加密"))
        self.label_9.setText(_translate("MainWindow", "加密内容"))
        self.label_10.setText(_translate("MainWindow", "私钥"))
        self.label_11.setText(_translate("MainWindow", "加密结果"))
        self.asymCombBox.setItemText(0, _translate("MainWindow", "RSA"))
        self.asymCombBox.setItemText(1, _translate("MainWindow", "DSA"))
        self.asymCombBox.setItemText(2, _translate("MainWindow", "ECC"))
        self.label_5.setText(_translate("MainWindow", "加密算法"))
        self.label_12.setText(_translate("MainWindow", "公钥"))
        self.asymDecipherBtn.setText(_translate("MainWindow", "解密"))
        self.asymEncryptionBtn.setText(_translate("MainWindow", "加密"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "非对称加密"))
        self.label_13.setText(_translate("MainWindow", "加密算法"))
        self.otherEncryptionBtn.setText(_translate("MainWindow", "加密"))
        self.otherCombBox.setItemText(0, _translate("MainWindow", "MD5"))
        self.otherCombBox.setItemText(1, _translate("MainWindow", "SHA1"))
        self.otherCombBox.setItemText(2, _translate("MainWindow", "Base64"))
        self.label_14.setText(_translate("MainWindow", "加密内容"))
        self.label_15.setText(_translate("MainWindow", "加密结果"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "其他加密"))
        self.injectBtn.setText(_translate("MainWindow", "注入"))
        self.label_16.setText(_translate("MainWindow", "测试Api："))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "注入测试"))
        self.label_17.setText(_translate("MainWindow", "网址"))
        self.leakScanBtn.setText(_translate("MainWindow", "检测"))
        self.leakScanStopBtn.setText(_translate("MainWindow", "停止"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("MainWindow", "漏洞检测"))


from PyQt5 import QtWebEngineWidgets
